#!/usr/bin/env python3
# -*- coding=utf-8 -*-
import json


def my_obj_pairs_hook(lst):
    result={}
    count={}
    for key,val in lst:
        if key in count:count[key]=1+count[key]
        else:count[key]=1
        if key in result:
            if count[key] > 2:
                result[key].append(val)
            else:
                result[key]=[result[key], val]
        else:
            result[key]=val
    return result


if __name__ == "__main__":
    with open('tt.json') as f:
        data = f.readlines()
        print(data)
        print(''.join(data))
        data = ''.join(data)
    tt = json.loads(data, object_pairs_hook=my_obj_pairs_hook)
    print(tt['project']['key'][1])

